backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/assets/media"
public_folder: "/assets/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "People"
    name: "people"
    label_singular: "person"
    folder: "src/content/people"
    create: true
    editor:
      preview: true
    summary: "{{title}}: {{date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Birth date", name: "date", widget: "datetime", date_format: "DD MMM YYYY", time_format: false, default: "", required: false }
      - { label: "Birth place", name: "birthPlace", widget: "string", required: false }
      - { label: "Death date", name: "deathdate", widget: "datetime", date_format: "DD MMM YYYY", time_format: false, default: "", required: false }
      - { label: "Death place", name: "deathPlace", widget: "string", required: false }
      - widget: select
        label: "Gender"
        name: "gender"
        multiple: false
        create: false
        options: ["Male", "Female", "Unknown"]
  - label: "Media"
    name: "media"
    folder: "src/content/media"
    summary: "{{title}}: {{caption}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Reference ID", name: "title", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        collapsed: false
        required: false
        field: {label: Image, name: image, widget: image}
      - { label: "Tags", name: "tags", widget: "list", required: false, hint: "Comma separated keywords that describe the image." }
      - { label: "Photo Paper ID", name: "paperId", widget: "list", required: false, hint: "Any unique paper ID markings on the back of the photo to help group sets." }
      - label: "Linked to"
        name: "relatedPeople"
        widget: "relation"
        collection: "people"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title", "date"]
        required: false
        multiple: true
        hint: "Link to people that you can identify in the photo"
      - widget: select
        label: "Media type"
        name: "mediaType"
        multiple: false
        create: false
        options: ["Portrait", "Headstone", "Document"]
        default: "Portrait"
      - { label: "Caption", name: "caption", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD MMM YYYY", time_format: false, default: "", required: false}
      - { label: "Location", name: "location", widget: "string", required: false}
      - { label: "Description", name: "description", widget: "string", required: false}
      - { label: "Transcription", name: "transcription", widget: "string", required: false}
      - label: "Similar to"
        name: "similarTo"
        widget: "relation"
        collection: "media"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title", "date"]
        required: false
        multiple: true