name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6062df026be1cad20554b303
